# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-07 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph',
            name='single_data',
            field=models.IntegerField(default=0, verbose_name='Single Data'),
        ),
        migrations.AlterField(
            model_name='graphdata',
            name='data',
            field=models.IntegerField(default=0, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='graphdata',
            name='label',
            field=models.CharField(max_length=250, verbose_name='Label'),
        ),
    ]
