# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-07 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0002_auto_20171007_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph',
            name='single_data',
            field=models.IntegerField(default=0, null=True, verbose_name='Single Data'),
        ),
    ]
